# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b34a117a2c39ea7af29cf403a520a2609cdfdb54ac997065ae66acfa7a117e73fb9a5d1f5ced8733ea4e61077f19d880feb766ab6120cc10bbb15e09baaf90e8

test:
  secret_key_base: 7c40a174865a6277f4051a700a8902857d23d66c0f2f3892061b9c3297414f6a65286f3ca85f87766ed210dc4fd48fdde6afb00257a4779b51d1c1f043e5c97e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
